apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/vottri/sap2503-final-lab.git'
    targetRevision: main
    path: charts/student-app
    helm:
      releaseName: student-app-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
